modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="lwl" #mandatory
version="1.0" #mandatory
displayName="Last World Loader" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# logoFile="textures/last-world-loader-icon.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Ripley2459" #optional
description='''Tired of pressing a button and clicking on the first world listed?
The Last World Loader simply add a button on the main menu: when pressed this button load the last singleplayer world played. WOW! Incredible.
Created for the New Elysium modpack.'''
[[dependencies.lwl]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.lwl]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
